import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from backend.app.review_prompts import PromptStore, build_reviewer_prompt_list


def _toml_string(value):
    return json.dumps(value, ensure_ascii=False)


def build_config(prompts_dir):
    store = PromptStore(prompts_dir)
    default_template = next(template for template in store.list_templates() if template["is_default"])
    reviewer_prompts = build_reviewer_prompt_list(prompts_dir)
    prompt_lines = ",\n".join(f"  {_toml_string(prompt)}" for prompt in reviewer_prompts)
    return f"""# Generated by .github/scripts/build_pr_agent_config.py
# Default review prompt: {default_template['id']}@{default_template['version']}

[config]
model = "gpt-5-mini"
model_turbo = "gpt-5-mini"
fallback_models = ["gpt-5-mini"]
custom_model_max_tokens = 128000
temperature = 1

[pr_reviewer]
model = "gpt-5-mini"
max_tokens = 3000
temperature = 1
reviewer_prompts = [
{prompt_lines}
]

[github]
access_token = "${{{{ secrets.GITHUB_TOKEN }}}}"

[openai]
model = "gpt-5-mini"
"""


def main():
    parser = argparse.ArgumentParser(description="Build pr-agent config from versioned review prompt templates.")
    parser.add_argument("--prompts-dir", default=".github/review-prompts")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    prompts_dir = Path(args.prompts_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_config(prompts_dir), encoding="utf-8")
    print(f"Generated pr-agent config from {prompts_dir} -> {output_path}")


if __name__ == "__main__":
    main()
