site_name: 《工程实践》在线网站
site_url: https://oaepp.uwis.cn
copyright: 成都信息工程大学 软件工程学院
nav:
  - 课程简介: index.md
  - 教学大纲: syllabus.md
  - 教师简介: instructor.md
  - 工程实践1-4概述:
      - 工程实践的作用与意义: overview_chapter1.md
      - 工程实践1-4的学习重点: overview_chapter2.md
  - 工程实践1:
      - 第1章: practice1_chapter1.md
      - 第2章: practice1_chapter2.md
      - 第3章: practice1_chapter3.md
  - 工程实践2:
      - 第4章: practice2_chapter1.md
      - 第5章: practice2_chapter2.md
      - 第6章: practice2_chapter3.md
  - 工程实践3:
      - 第7章: practice3_chapter1.md
      - 第8章: practice3_chapter2.md
      - 第9章: practice3_chapter3.md
  - 工程实践4:
      - 第10章 软件产品介绍: 第10章_软件产品介绍.md
      - 第11章 开发流程介绍: 第11章_开发流程介绍.md
      - 第12章 项目管理: 第12章_项目管理.md
  - 附录:
      - 附录A CubeMX编程指南: appendix_a.md
      - 附录B 实验用容器与开发环境: appendix_b.md
      - 附录C STM32实践项目集: appendix_c.md
  - 书写规范: contributing.md
  - 参考资料: resources.md
theme:
  name: material
  features:
    - navigation.expand

extra_css:
  - assets/stylesheets/exam-login.css

extra_javascript:
  - assets/javascripts/exam-login.js
  - assets/javascripts/footer-links.js
  - assets/javascripts/lib/mermaid.min.js
  - assets/javascripts/mermaid-init.js
  - assets/javascripts/utterances.js

plugins:
  - search:
      lang:
        - zh
        - en
  - mkdocs_quiz
  - kroki:
      fence_prefix: kroki-
      enable_mermaid: false

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2-4
  - pymdownx.superfences
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
      format: svg
  - markdown_svgbob:
      tag_type: inline_svg
      bg_color: white
      fg_color: black
      min_char_width: 80